flights/urls.py
from django.urls import path
from . import views

app_name = "flights"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book"),
]

hello_world/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('tasks/', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('flights/', include('flights.urls')),
    path('newyear/', include('newyear.urls')),
    path('simple-app/', include('simple_app.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns =  [
    path("", views.index, name="index")
]

newyear/urls.py
from django.urls import path
from . import views

app_name = 'newyear'
urlpatterns =  [
    path("", views.index, name="index")
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("<int:task_id>", views.task, name="task"),
    path("<int:task_id>/update", views.update, name="update"),
]

users/urls.py
from django.urls import path
from . import views
from .views import SignUpView

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("register", views.register_view, name="register"),
]

home/views.py
from django.shortcuts import render

def index(request):
    return render(request, "home/index.html")

home/templates/home/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Home</title>
    </head>
    <body>
        <h1>Applications</h1>
        <ul>
            <li><a href="{% url 'home:index' %}">Home</a></li>
            <li><a href="{% url 'newyear:index' %}">New Year</a></li>
            <li><a href="{% url 'simple_app:index' %}">Simple App</a></li>
            <li><a href="{% url 'tasks:index' %}">Tasks (TODO List)</a></li>
            <li><a href="{% url 'users:index' %}">Users</a></li>
            <li><a href="{% url 'flights:index' %}">Flights</a></li>
            <li><a href="/jobs">Jobs (API Example)</a></li>
        </ul>
    </body>
</html>