hello_world/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('tasks/', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('flights/', include('flights.urls')),
    path('newyear/', include('newyear.urls')),
    path('simple-app/', include('simple_app.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns =  [
    path("", views.index, name="index")
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("<int:task_id>", views.task, name="task"),
    path("<int:task_id>/update", views.update, name="update"),
]

tasks/models.py
from django.db import models

class Task(models.Model):
    title = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.id}: {self.title}"

tasks/forms.py
from django import forms
from .models import Task

class NewTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from .forms import NewTaskForm
from .models import Task

def index(request):
    tasks = Task.objects.all()

    return render(request, "tasks/index.html", {
        "tasks": tasks
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("tasks:index")
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

def task(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
        form = NewTaskForm(instance=task)
        return render(request, "tasks/task.html", {
            "task": task,
            "form": form
        })
    except:
        return HttpResponseBadRequest("Task not found")

def update(request, task_id):
    if request.method == "POST":
        task = Task.objects.get(pk=task_id)
        form = NewTaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("tasks:task", task_id=task_id)
        else:
            return render(request, "tasks/task.html", {
                "task": task,
                "form": form
            })
    else:
        return HttpResponseBadRequest("Invalid Method")

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>Add Task:</h1>
        <form action="{% url 'tasks:add'%}" method="post">
            {% csrf_token %}
            {{ form.title }}
            <input type="submit">
        </form> 
        <a href="{% url 'tasks:index' %}">View tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>Your tasks are:</h1>
        <table style="width:100%">
        {% if tasks %}
            <ul>
            {% for task in tasks %}
                <li><a href="{% url 'tasks:task' task.id %}">{{ task }}</a> {% if task.completed %} - Done {% endif %}</li>
            {% endfor %}
            </ul>
        {% else %}
            <h3>No tasks</h3>
        {% endif %}
        </table>
        <a href="{% url 'tasks:add' %}">Add new tasks</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

tasks/templates/tasks/task.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>Task #{{ task.id }} information</h1>
        <ul>
            <li>Title: {{ task.title }}</li>
            <li>Is completed: {% if task.completed %} Yes {% else %} No {% endif %}</li>
            <li>Creation Date: {{ task.creation_date }}</li>
        </ul>
        <h2>Update task information</h2>
        <form method="POST" action="{% url 'tasks:update' task.id %}">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <a href="{% url 'tasks:index' %}">View tasks</a>
{% endblock %}