hello_world/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('tasks/', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('flights/', include('flights.urls')),
    path('newyear/', include('newyear.urls')),
    path('simple-app/', include('simple_app.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns =  [
    path("", views.index, name="index")
]

users/urls.py
from django.urls import path
from . import views
from .views import SignUpView

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("register", views.register_view, name="register"),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import generic

def index(request):
    if not request.user.is_authenticated:
        return redirect("users:login")

    return render(request, "users/user.html", {
        "count": User.objects.count()
    })

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("users:index")
        else:
            return render(request, "users/login.html", {
                "message": "Invalid credentials."
            })
    return render(request, "users/login.html")

def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("users:index")
        else:
            return render(request, "users/register.html", {
                "form": form
            })
    
    form = UserCreationForm()
    return render(request, "users/register.html", {
        "form": form
    })

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = "users/signup.html"

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "Logged out."
    })

users/templates/users/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Users</title>
    </head>
    <body>
    {% block body %}{% endblock %}
    </body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}
    {% if message %}
    <div>{{ message }}</div>
    {% endif %}
    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>
    <a href="{% url 'users:register' %}">Create a new account. (Register)</a> <br/>
    <a href="{% url 'users:signup' %}">Create a new account. (Sign up)</a>
{% endblock %}

users/templates/users/register.html
{% extends "users/layout.html" %}

{% block body %}
    <form action="{% url 'users:register' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

users/templates/users/signup.html
{% extends "users/layout.html" %}

{% block body %}
    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Sign Up">
    </form>
{% endblock %}

users/templates/users/user.html
{% extends "users/layout.html" %}

{% block body %}
    <h1> Welcome, {{ request.user.username }} </h1>
    <ul>
        <li>Username: {{ request.user.username }}</li>
        {% if request.user.email %}<li>email: {{ request.user.email }}</li>{% endif %}
        {% if request.user.first_name and request.user.last_name %}<li>Name: {{ request.user.first_name }} {{ request.user.last_name }}</li>{% endif %}
    </ul>
    <p><strong>Total registered users: </strong> {{ count }}</p>
    <a href="{% url 'users:logout' %}"> Logout </a>
{% endblock %}