flights/urls.py
from django.urls import path
from . import views

app_name = "flights"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book"),
]

hello_world/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('tasks/', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('flights/', include('flights.urls')),
    path('newyear/', include('newyear.urls')),
    path('simple-app/', include('simple_app.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns =  [
    path("", views.index, name="index")
]

flights/models.py
from django.db import models

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

class Passenger(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

flights/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseBadRequest
from .models import Flight, Passenger

def index(request):
    return render(request, "flights/index.html", {
        "flights": Flight.objects.all()
    })

def flight(request, flight_id):
    try:
        flight = Flight.objects.get(pk=flight_id)
        return render(request, "flights/flight.html", {
            "flight": flight,
            "passengers": flight.passengers.all(),
            "non_passengers": Passenger.objects.exclude(flights=flight).all()
        })
    except:
        return HttpResponseBadRequest("Flight not found")

def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger = Passenger.objects.get(pk=int(request.POST["passenger"]))
        passenger.flights.add(flight)
        return redirect("flights:flight", flight_id=flight_id)

flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
        {% if flight %}
        <h1>Flight #{{ flight.id }}</h1>
        <ul>
            <li>Origin: {{ flight.origin }}</li>
            <li>Destination: {{ flight.destination }}</li>
            <li>Duration: {{ flight.duration }}</li>
        </ul>
        <h2>Passengers</h2>
        {% if passengers %}
        <ul>
        {% for passenger in passengers %}
            <li>{{ passenger.id }} - {{ passenger }}</li>
        {% endfor %}
        </ul>
        {% else %}
        No passengers
        {% endif %}            
        <h2>Add Passenger</h2>
        <form method="POST" action="{% url 'flights:book' flight.id %}">
            {% csrf_token %}
            {% if non_passengers %}
            <select name="passenger">
            {% for non_passenger in non_passengers %}
                <option value="{{ non_passenger.id }}">{{ non_passenger }}</option>
            {% endfor %}
            </select>
            {% else %}
            No passengers can book this flight.
            {% endif %}
            <input type="submit">
        </form>
        {% endif %}
        <a href="{% url 'flights:index' %}">Go back to flights page.</a>
{% endblock %}

flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
        <h1>Flights</h1>
        {% if flights %}
            <ul>
            {% for flight in flights %}
                <li>Flight {{ flight.id }}:
                    <a href="{% url 'flights:flight' flight.id %}">
                    {{ flight.origin }} to {{ flight.destination }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <h3>No flights</h3>
        {% endif %}
{% endblock %}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Flights</title>
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>